version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "23:30"
  open-pull-requests-limit: 40
  ignore:
  - dependency-name: html-webpack-plugin
    versions:
    - 4.5.0
    - 4.5.1
  - dependency-name: mini-css-extract-plugin
    versions:
    - 1.3.3
    - 1.3.5
  - dependency-name: webpack-cli
    versions:
    - 4.3.1
    - 4.4.0
  - dependency-name: "@babel/core"
    versions:
    - 7.12.10
  - dependency-name: eslint-plugin-react
    versions:
    - 7.22.0
  - dependency-name: "@babel/cli"
    versions:
    - 7.12.10
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.12.11
  - dependency-name: "@babel/preset-react"
    versions:
    - 7.12.10
  - dependency-name: css-loader
    versions:
    - 5.0.1
  - dependency-name: bootstrap
    versions:
    - 4.5.3
  - dependency-name: webpack
    versions:
    - 4.44.2
  - dependency-name: enzyme-adapter-react-16
    versions:
    - 1.15.5
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: elliptic
    versions:
    - 6.5.3
